### ISSUE TITLE
Throw exception if File::Temp can't create temporary file

### ISSUE THREAD

**Issue by tokuhirom** [perlpilot/p6-File-Temp#12]
Current implementation returns empty list if File::Temp can't create temporary file.
https://github.com/perlpilot/p6-File-Temp/blob/master/lib/File/Temp.pm#L32

But it cause a programming issue in user's code. I recommend to throw exception if it can't create temporary file.

**Comment by rudis** [comment]
Seconded. Removes useless checks in all programs. Please raise an exception.

**Comment by perlpilot** [comment]
As of 00daa46ff2330baa5dae1319e85399e65a546435 it now fails when it can't create a file/dir.
